version: '3.4'

services:
  processflow.api:
    image: ${DOCKER_REGISTRY-}processflowapi
    build:
      context: .
      dockerfile: ProcessFlow.API/Dockerfile
    depends_on:
      - db
    environment:
      - DATABASE_URL=Server=localhost,1433;Database=ProcessFlow;User ID=sa;Password=YourStrong!Passw0rd;Trusted_Connection=False; TrustServerCertificate=True;
  db:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sqlserver
    restart: always
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"